<?php 
    $_helper = $this->helper('Smartwave\Porto\Helper\Cssconfig');
    $porto_helper = $this->helper('Smartwave\Porto\Helper\Data');
    $page_layout = $this->getConfig('porto_settings/general/layout');
    if($page_layout == "full_width") {
        $page_layout = "layout-fullwidth";
    } else if($page_layout == "1140") {
        $page_layout = "layout-1140";
    } else if($page_layout == "1280") {
        $page_layout = "layout-1280";
    }
    $boxed = $this->getConfig('porto_settings/general/boxed');
?>
<?php
    $header_type = $this->getConfig('porto_settings/header/header_type');
?>
<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
<link rel="stylesheet" type="text/css" media="print" onload="this.media='all'" href="<?php echo $_helper->getDesignFile()?>">
<link rel="stylesheet" type="text/css" media="print" onload="this.media='all'" href="<?php echo $_helper->getSettingsFile()?>">
<script type="text/javascript">
require([
    'jquery'
], function ($) {
    $(document).ready(function(){
        $(".drop-menu > a").off("click").on("click", function(){
            if($(this).parent().children(".nav-sections").hasClass("visible"))
                $(this).parent().children(".nav-sections").removeClass("visible");
            else
                $(this).parent().children(".nav-sections").addClass("visible")
        });
    });
});
</script>
<?php if($this->getConfig('porto_settings/general/smartlayers')): ?>
<?php endif; ?>